version: '3.3'
services:
  zandronum-server:
    #build: .
    build:
      context: .
      args:
        - MODE=server
    hostname: zandronum-server
    restart: unless-stopped
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./player/whitelist.txt:/home/zandronum/player/whitelist.txt:ro
      - ./player/banlist.txt:/home/zandronum/player/banlist.txt:rw
      - ./player/adminlist.txt:/home/zandronum/player/adminlist.txt:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    ports:
      - 10667:10667/udp
    networks:
      zandro-net:
        ipv4_address: 192.168.167.10
    environment:
      - MODE=server
    image: innovanon/docker-zandronum-server:latest
    container_name: docker-zandronum-server

  zandronum-client:
    privileged: true
    #build: .
    build:
      context: .
      args:
        - MODE=client
    hostname: zandronum-client
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      #- doom-logs:/home/zandronum/log/:rw
      # TODO
      #- /tmp/.X11-unix:/tmp/.X11-unix:ro 
      #- /etc/localtime:/etc/localtime:ro
      - $XAUTHORITY:$XAUTHORITY
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /etc/localtime:/etc/localtime:rw
    devices:
      # old
      #- "/dev/snd/controlC0:/dev/snd"
      # new
      #- "/dev/snd/controlC0:/dev/snd/controlC0"
      #- "/dev/snd/hwC0D0:/dev/snd/hwC0D0"
      #- "/dev/snd/pcmC0D0c:/dev/snd/pcmC0D0c"
      #- "/dev/snd/pcmC0D0p:/dev/snd/pcmC0D0p"
      #- "/dev/snd/pcmC0D2c:/dev/snd/pcmC0D2c"
      #- "/dev/snd/pcmC0D2p:/dev/snd/pcmC0D2p"
      #- "/dev/snd/seq:/dev/snd/seq"
      #- "/dev/snd/timer:/dev/snd/timer"
      # newer
      - "/dev/snd"
    # TODO segfault Address: 0x38
    networks:
      - zandro-net
    #network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY
      - MODE=client
    image: innovanon/docker-zandronum-client:latest
    container_name: docker-zandronum-client
    depends_on:
      - "zandronum-server"

volumes:
  doom-logs:
  abaddonvol:
    external: true
  wadsvol:
    external: true
  clientcfg:

networks:
  zandro-net:
    ipam:
      config:
      - subnet: 192.168.167.0/24

